{{- if .Values.shophubApi.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "shophub.apiName" . }}
  labels:
    {{- include "shophub.apiLabels" . | nindent 4 }}
{{- end }}
